# Generated by Django 5.2.8 on 2025-11-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['fecha'], 'permissions': [('puede_editar_evento', 'Puede editar evento'), ('puede_crear_evento', 'Puede crear evento')]},
        ),
    ]
