# Generated by Django 6.0 on 2025-12-14 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('conferencia', 'Conferencia'), ('concierto', 'Concierto'), ('seminario', 'Seminario')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('es_privado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asistentes', models.ManyToManyField(blank=True, related_name='eventos_asistidos', to=settings.AUTH_USER_MODEL)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
