# Generated by Django 5.2.8 on 2025-11-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, help_text="Ruta relativa en static, ej. 'images/miimagen.jpg'", max_length=255),
        ),
    ]
